# Generated by Django 5.1.1 on 2024-09-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crud',
            name='booleano',
            field=models.BooleanField(default=0, verbose_name='Boleano'),
        ),
        migrations.AddField(
            model_name='crud',
            name='correo',
            field=models.EmailField(max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='crud',
            name='decimal',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True, verbose_name='Decimal'),
        ),
        migrations.AddField(
            model_name='crud',
            name='fecha',
            field=models.DateField(null=True, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='crud',
            name='numero',
            field=models.IntegerField(null=True, verbose_name='Número'),
        ),
    ]
