# Generated by Django 5.1.1 on 2024-09-19 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_crud_booleano_crud_correo_crud_decimal_crud_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crud',
            name='booleano',
        ),
    ]
