# Generated by Django 5.1.1 on 2024-09-19 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_remove_crud_booleano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crud',
            name='decimal',
        ),
    ]
