# Generated by Django 5.1.1 on 2024-10-22 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_alter_crud_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crud',
            name='fecha',
        ),
    ]
