# Generated by Django 5.1.1 on 2024-10-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_remove_crud_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='crud',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
