# Generated by Django 5.1.1 on 2024-10-22 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_crud_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='foranea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreForaneo', models.CharField(max_length=20, verbose_name='Nombre Foraneo')),
                ('nombreForaneoB', models.CharField(max_length=20, verbose_name='Nombre ForaneoB')),
                ('eleccion', models.CharField(choices=[('A', 'Opcion 1'), ('B', 'Opcion 2')], default='A', max_length=20)),
            ],
            options={
                'verbose_name': 'Foranea',
                'verbose_name_plural': 'Foraneas',
                'db_table': 'foranea',
                'ordering': ['nombreForaneo', '-nombreForaneoB'],
            },
        ),
        migrations.AddField(
            model_name='crud',
            name='campoForaneo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.foranea'),
        ),
    ]
